# Site settings
title: Zi's website
url: https://weirdkittyz.github.io/
skills: "Hungry Scatterer - Amateur Artist & Photographer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a3d47b
  primary-rgb: "163, 212, 123"
  secondary: 69c8c3
  secondary-dark: 3cbeb7

# Footer settings
footer:
  copyright: Yijia Zi
  social: Social

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/WeirdKittyZ
  - title: linkedin
    url: https://www.linkedin.com/in/yijia-zi-644634178/
  - title: instagram
    url: https://www.instagram.com/z._1896528?igsh=aWh5ZzlnZTJoM3Rp&utm_source=qr
   - title: discus
    url: mailto://zyjzjq99@sina.com

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
